name: 'package-action'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
#   push:
#     branches:
#       - main
#       - 'releases/*'
  workflow_dispatch:
  release: 

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Checking out!
        uses: actions/checkout@v3
        # with:
        #   ref: 'Give optional branch name/SHA/tag to checkout' 
  
      # The ORAS cli, possibly will be baked in runner-vm and this step will not be required
      - name: Install Oras
        run: |
          curl -LO https://github.com/oras-project/oras/releases/download/v0.12.0/oras_0.12.0_linux_amd64.tar.gz
          mkdir -p oras-install/
          tar -zxf oras_0.12.0_*.tar.gz -C oras-install/
          mv oras-install/oras /usr/local/bin/
          rm -rf oras_0.12.0_*.tar.gz oras-install/
          echo "Oras installed!"
          
      - name: Login to ghcr
        run: echo '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' | oras login ghcr.io  -u vinayakanamarlapudi --password-stdin
        # run: oras login ghcr.io '-u' repositoryOwner -p ${{ secrets.GITHUB_TOKEN }}
#       
      - name: Uploading to ghcr
        run: oras push ghcr.io/vinaykanamarlapudi/fp:1.0.0 --manifest-config /dev/null:application/vnd.actions.packages ./:application/vnd.actions.packages.layer.v1+tar
#       - name: Running action   
#         uses: ruchika-jain/package-action@1.0.1
#         with:
#           package-name: 'hello-ghcr-upload'
#         id: publish-action
